name: gtkx-snap
base: core24
version: '0.1'
summary: GTKX Snap
description: GTKX Snap

grade: devel
# Use devmode for development (no strict confinement)
confinement: devmode

platforms:
  amd64:

parts:
  gtkx-snap-part:
    # Use 'nil' plugin to run custom build commands
    plugin: nil
    source: .
    # We need the Node snap for the build tools (npm/node)
    build-snaps:
      - node/24/stable
    build-packages:
      - wget
    #      - ca-certificates

    # We do this during the build phase so it doesn't end up in the final snap
    override-build: |
      NODE_VERSION=$(node -v)
      NODE_DIST="node-$NODE_VERSION-linux-x64"
      NODE_URL="https://nodejs.org/dist/$NODE_VERSION/$NODE_DIST.tar.gz"
      
      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/gui
      
      cp ./assets/icon.png $CRAFT_PART_INSTALL/gui/
      cp ./assets/app.desktop $CRAFT_PART_INSTALL/gui/
      
      # 6. Copy native module
      cp ./dist/index.node $CRAFT_PART_INSTALL/bin/index.node
      cp ./dist/app $CRAFT_PART_INSTALL/bin/app
      ls $CRAFT_PART_INSTALL/bin

    # CRITICAL: This acts like the "clean" step in Docker
    # We only include the final binary. nothing else.
    prime:
      - bin/app
      - bin/index.node
      - gui/

apps:
  gtkx-demo:
    command: bin/app
    desktop: gui/app.desktop
    # Automatically configure GNOME environment
    extensions: [ gnome ]
    environment:
      # This fixes the libpxbackend-1.0.so missing error
      LD_LIBRARY_PATH: $SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET/libproxy:$LD_LIBRARY_PATH
